exclude: |
  (?x)(
    ^data/
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: trailing-whitespace
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']
        files: \.(json|template)$
  # https://docs.astral.sh/ruff/integrations/#pre-commit
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix, --unsafe-fixes, --exit-non-zero-on-fix, --output-format=full]
        types_or: [python, pyi, jupyter]
      # Run the formatter
      - id: ruff-format
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        types: [jupyter]
  - repo: local
    hooks:
      - id: remove-version-metadata
        name: remove version metadata from ipynb files
        entry: python .pre-commit/remove_kernelspec.py
        language: system
        types: [jupyter]
